### ISSUE TITLE
ApplicationManagement oninstall and onuninstall handler argument

### ISSUE THREAD

**Issue by jmajnert** [sysapps/runtime#19]
For the oninstall and onuninstall handlers, the spec says: "The only argument to this function will be the AppObject of the application that was (un)installed".
 The AppObject is not defined in the spec. Should it be Application object or maybe one of the types defined in Application Event Types (please also see issue https://github.com/sysapps/runtime/issues/18  )?

**Comment by mounirlamouri** [comment]
This has been fixed by commit 257d8ca.
