### ISSUE TITLE
"web notifications" instead of "desktop-notification"

### ISSUE THREAD

**Issue by jmajnert** [sysapps/runtime#21]
Chapter 9.3 of the runtime spec says "Allow the application to use the Desktop Notification API."

I'm wondering if this shouldn't be "Allow the application to use the Web Notifications API" ?

**Comment by mounirlamouri** [comment]
This isssue has been fixed by the PR 23. Thanks :)

**Comment by mounirlamouri** [comment]
For bookkeeping, it has been solved by commit eb36ea023b.
