### ISSUE TITLE
Remove ApplicationManagement interface

### ISSUE THREAD

**Issue by mounirlamouri** [sysapps/runtime#4]
There is a [discussion going on in the mailing-list](http://lists.w3.org/Archives/Public/public-sysapps/2013Mar/0017.html) and we should consider, _maybe_, removing this interface. If we remove it we could whether add it later or in another specification.

**Comment by marcoscaceres** [comment]
Added link to discussion thread in the description.

**Comment by mounirlamouri** [comment]
After discussing this in the F2F, the resolution was to not remove this interface for the moment and that we might, maybe move it to another specification if there is such a request.
