### ISSUE TITLE
Make clear that the application manifest isn't only for installable apps

### ISSUE THREAD

**Issue by mounirlamouri** [sysapps/runtime#42]
There should be some means to make allow hosted apps to be "auto discoverable" by search engines and user agents.

**Comment by anssiko** [comment]
Re manifest, I'd like to see us provide web developers a clear migration path from "traditional" web applications to "packaged" web applications. I believe that splitting the "Application Manifest" section into its own spec with no dependencies to the rest of the runtime spec would help get currently proprietary <meta> and <link> features standardized for the "traditional" web applications too.

**Comment by marcoscaceres** [comment]
@anssiko I tend to agree that splitting into a separate document would be helpful (though I can live with what we currently have). I have most of the manifest, processing, and i18n model done in a separate doc already.

**Comment by marcoscaceres** [comment]
It might be helpful to link to this from the spec: http://www.w3.org/community/webappstore/wiki/Manifest

**Comment by marcoscaceres** [comment]
@anssiko just a note, we don't want to encourage people to make packaged apps (those should really be reserved for the small subset that need to be put into a zip file). We want to encourage app developers to use hosted web apps instead. To do that, we need to get consensus to add _something_ to HTML to make it easy to associate a manifest with an application. If that fails, I guess we can just keep using the install() method.

**Comment by marcoscaceres** [comment]
Moved to: https://github.com/sysapps/manifest/issues/13
