### ISSUE TITLE
Clarify that screen_size is defined in CSS units

### ISSUE THREAD

**Issue by kenchris** [sysapps/runtime#47]
This is important as the web apps are defined in CSS units and many new devices have dppx != 1.0

**Comment by marcoscaceres** [comment]
I've got some text for this that I will push soon.

**Comment by marcoscaceres** [comment]
@kenchris can you please check [3.14 screen_size member](http://runtime.sysapps.org/#screen_size-member) and let me know know if the text is ok?

**Comment by kenchris** [comment]
Looks good to me!
