### ISSUE TITLE
ZIP reference standard

### ISSUE THREAD

**Issue by hollobit** [sysapps/runtime#58]
"[ZIP] Reference not found."

I think it can be change as below 

[ZIP] ISO/IEC NP 21320-1 - Information technology -- Document Container File -- Part 1: Core  URL: http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=60101

**Comment by marcoscaceres** [comment]
I added the Zip ref to Respec's biblio yesterday. Will start working when the next update to respec is released.
