### ISSUE TITLE
i18n model is not specified

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/runtime#6]
The spec currently eludes to an internationalization model, but the behaviour of that model is not specified.  

As the current document is based on Firefox OS I've also documented [Firefox OS's internationalization model and outlined some issues](https://gist.github.com/marcoscaceres/5055717) as well as possible solutions. I've presented those issues to [the W3C's i18n WG](http://lists.w3.org/Archives/Public/www-international/2013JanMar/0305.html).

**Comment by mounirlamouri** [comment]
We should think about RTL/LTR issues.

**Comment by mounirlamouri** [comment]
Isn't that fixed by #70?

**Comment by marcoscaceres** [comment]
sure is :)
