### ISSUE TITLE
App URI scheme section is underspecified

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/runtime#74]
The app:// URI scheme section of the spec is underspecified. Would be better to just link to http://appuri.sysapps.org/

**Comment by mounirlamouri** [comment]
On 16/04/13 16:43, Marcos Caceres wrote:

> The app:// URI scheme section of the spec is underspecified. Would be
> better to just link to http://appuri.sysapps.org/

Referencing http://appuri.sysapps.org/ LGTM.
