### ISSUE TITLE
Need to clarify installed/uninstalled/updated and multiple RuntimeInstallers

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/runtime#82]
Unclear behavior if the same application is installed/uninstalled/updated by more than on RuntimeInstaller. Since each system application can access its own RuntimeInstaller via window.runtime.installer, if Foo app initiates an operation to uninstall application, while at the moment, another Bar app also initiates another operation to uninstall the same application, then the expected behavior is not defined. Should RuntimeInstaller in Bar app can also receive onUninstall event if Foo app uninstall the app successfully.

**Comment by mounirlamouri** [comment]
RuntimeInstaller isn't part of the spec.

**Comment by marcoscaceres** [comment]
(I think I copied this stuff out of an email? ... don't remember now.)
