### ISSUE TITLE
Manifest format should support some way of including a splash screen

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/runtime#84]
(this is a clone of https://github.com/sysapps/sysapps/issues/41. Please see that bug for discussion and proposals)

Various vendors have expressed an interest in having a splash screen for when an app boots up.

Previous attempt at standardising such a thing:

https://dvcs.w3.org/hg/nativeapps/raw-file/tip/splashscreen/Overview.html

It might be good to reopen the discussion on sysapps.

Use case:
Because of the limited processing capabilities of some devices and the amount of time it takes to initialize a Web runtime, there can be a small - yet noticeably perceivable - delay between when the end-user starts an application and the application actually becoming available and interactive to the end-user.

Depending on the complexity of the application and the processing power of the device, this delay can range from a few milliseconds to a couple of seconds. When applications take more than a few seconds to load, it can be disorienting to end-users as nothing is displayed on the screen; leading to a poor user experience. Native applications overcome this issue by allowing developers to use a media file that is displayed the instant the application is launched. Such a file is commonly referred to as a "splash screen" or "launch image".

**Comment by hollobit** [comment]
I think it would be good to add the splash property as supported on BB's configuration. 

http://www.w3.org/community/webappstore/wiki/Manifest
https://developer.blackberry.com/html5/documentation/rim_splash_element.html

---- Proposed text ---- 

3.x splash member

The splash member is an object that represents the image to display on the screen while the application loads.
Paths beginning with "/" are treated as relative to the origin of the app.

**Comment by marcoscaceres** [comment]
@hollobit thanks for the proposed text. We have not received a lot of demand for this feature from other potential implementers, so it's going to be labelled LATER (thought not sure if we will just put into a LATER milestone or close the bug).

**Comment by marcoscaceres** [comment]
Moved to: https://github.com/sysapps/manifest/issues/9
