### ISSUE TITLE
Definition of required_features is wrong

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/runtime#88]
required_features is not really to enable features, just to filter out some applications from the stores

**Comment by jmajnert** [comment]
Do we have a list of features that can be listed as required? How does it correspond to the permissions member? IIRC in BONDI/WAC these two categories were covered by <feature> elements.

**Comment by marcoscaceres** [comment]
I don't have a list yet, no. I need to investigate how FxOS (or their store) handles this one.

**Comment by marcoscaceres** [comment]
Moved to: https://github.com/sysapps/manifest/issues/8
