### ISSUE TITLE
Change contributor name

### ISSUE THREAD

**Issue by hollobit** [sysapps/runtime#91]
Please change my name from Jonathan Jeon to 전종홍(Jonathan Jeon) in Appendix B. Acknowledgments

**Comment by marcoscaceres** [comment]
@hollobit, please fork the spec and send a pull request with this fix.

**Comment by hollobit** [comment]
@marcoscaceres Unfortunately, I'm a novice user to the github system. I'm trying to learn this system now. When I finish my study, I will try to fix it  Thanks for your advice. :)
